---
services:
  db:
    image: venkatadeepthi/pyapp:db_image
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
    networks:
      -  mynetwork
  auth_service:
    image: venkatadeepthi/pyapp:auth_image
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
    networks:
      -  mynetwork  
    depends_on:
      - db
  book_service:
    image: venkatadeepthi/pyapp:book_image
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
    networks:
      -  mynetwork  
    depends_on:
      - db
  borrow_service:
    image: venkatadeepthi/pyapp:borrow_image
    ports:
      - "5003:5003"
    deploy:
      replicas: 1
    networks:
      -  mynetwork  
    depends_on:
      - db
  app_service:
    image: venkatadeepthi/pyapp:app_image
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
    networks:
      -  mynetwork  
    depends_on:
      - auth_service
      - book_service
      - borrow_service
networks:
  mynetwork:
    driver:  overlay
